### ISSUE TITLE
sls deploy to google cloud function failed behind a proxy

### ISSUE THREAD

**Issue by karanrk** [serverless/serverless-google-cloudfunctions#151]
Hello Team,

I have followed your documentation to set up serverless and google cloud credentials on my machine which is sitting behind a proxy. I have exported the proxy variable, yet serverless fails to establish a connection to google cloud.

Error : Client network socket disconnected before secure TLS connection was established 

Stack Trace -

Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1179:19)
    at Object.onceWrapper (events.js:285:13)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:439:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:400:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:431:17)
    at variables.populateService.then.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:114:33)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:101:6)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:28)
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
    at /usr/local/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqCallback.args [as oncomplete] (fs.js:146:20)
From previous event:
    at initializeErrorReporter.then (/usr/local/lib/node_modules/serverless/bin/serverless:43:6)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)

Steps followed -
the code snippet at  serverless-google-cloudfunctions/provider/googleProvider.js

cloudfunctions: google.cloudfunctions({version:'v1', proxy: '<myproxy>'})

it didn't work, any help would be appreciated.

**Comment by karanrk** [comment]
Tried passing proxy parameters with google.options, it tries to connect to localhost which errors out eventually.

**Comment by perryao** [comment]
@karanrk I ran into the same issue. What worked for was creating my own plugin that uses a package called `global-tunnel-ng` to globally configured http clients to respect proxy variables in the environment. 

Here's the plugin:

```javascript
const globalTunnel = require('global-tunnel-ng');

class ProxyPlugin {
  constructor() {
    this.commands = {
      deploy: {
        lifecycleEvents: [
          'resources',
        ]
      },
    };
    this.hooks = {
      'before:deploy:resources': this.beforeDeployResources,
    };
  }

  beforeDeployResources() {
    const proxy = process.env.HTTP_PROXY
      || process.env.http_proxy
      || process.env.HTTPS_PROXY
      || process.env.https_proxy;
    if (proxy) {
      const url = new URL(proxy);
      globalTunnel.initialize({
        host: url.hostname,
        port: url.port,
        proxyAuth: `${url.username}:${url.password}`,
      });
      console.log('Proxy: configured globalTunnel via proxy')
    }
  }
}

module.exports = ProxyPlugin;
```

If you paste that into `.serverless_plugins/serverless-proxy/index.js` and update serverless.yml like so:

```yaml
plugins:
  - serverless-proxy
  - serverless-google-cloudfunctions
```
it should work.
You'll also need to `npm install global-tunnel-ng`

This comment over on another googleapis package led me to this solution: https://github.com/googleapis/nodejs-storage/issues/277#issuecomment-438574401

Certainly not a permanent fix, but should help until a fix is made in this package.

**Comment by karanrk** [comment]
@perryao that worked like a charm, Thank you!

Any idea how would edit your plugin to make it work for the 'before:invoke:invoke' hook too?

**Comment by karanrk** [comment]
'before:invoke:invoke': this.beforeDeployResources  - this worked too!
