### ISSUE TITLE
sls remove: Error: Not Found

### ISSUE THREAD

**Issue by mrdulin** [serverless/serverless-google-cloudfunctions#178]
# This is a Bug Report

## Description

- What went wrong?

When I run `sls remove` command, got `Error: Not Found`

- What did you expect should have happened?

So I go to read the source code, found the reason: 

```js
getObjectsToRemove() {
    const params = {
      bucket: this.serverless.service.provider.deploymentBucketName
    };

    return this.provider
      .request('storage', 'objects', 'list', params)
      .then(response => {
        if (!response.items || !response.items.length) return BbPromise.resolve([]);

        return BbPromise.resolve(response.items);
      })
      .catch(error => {
        console.log('getObjectsToRemove error: ', error);
      });
  },
```

If there are no objects in cloud storage which means the objects were deleted manually by me. It's better to check if objects exist. If the objects exist, then remove them, otherwise, should skip this operation.

- What stacktrace or error message from your provider did you see?

```bash
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke remove
 
  Error --------------------------------------------------
 
  Error: Not Found
    at createError (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at GoogleRemove.emptyDeploymentBucket (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless-google-cloudfunctions/remove/lib/emptyDeploymentBucket.js:8:8)
From previous event:
    at Object.remove:remove [as hook] (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless-google-cloudfunctions/remove/googleRemove.js:34:10)
    at BbPromise.reduce (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless/lib/classes/PluginManager.js:464:55)
From previous event:
    at PluginManager.invoke (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless/lib/classes/PluginManager.js:464:22)
    at PluginManager.run (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless/lib/classes/PluginManager.js:496:17)
    at variables.populateService.then (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless/lib/Serverless.js:116:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Serverless.run (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless/lib/Serverless.js:103:74)
    at serverless.init.then (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless/bin/serverless.js:60:28)
    at /Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:57:14
    at /Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
From previous event:
    at initializeErrorReporter.then (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless/bin/serverless.js:60:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Object.<anonymous> (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/serverless/bin/serverless.js:46:39)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.0
     Framework Version:         1.50.0
     Plugin Version:            1.3.8
     SDK Version:               2.1.0
 
```

Add debug logs:

```bash
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Invoke remove
getObjectsToRemove error:  { Error: Not Found
    at createError (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/ldu020/workspace/github.com/mrdulin/nodejs-serverless-framework/samples/GCP/quick-start/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by pmuens** [comment]
Thanks for reporting @mrdulin 👍

I'll close this one since #186 covers a more generic version of this problem.
