### ISSUE TITLE
Invalid runtime

### ISSUE THREAD

**Issue by KhadijaBenAmmar** [serverless/serverless-google-cloudfunctions#189]
On sls deploy:
I am getting this error: 
```Error: Deployment failed: RESOURCE_ERROR

     {"ResourceType":"cloudfunctions.v1beta2.function","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"runtime","description":"Invalid runtime."}]}],"statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1beta2/projects/algoan-dev/locations/us-central1/functions","httpMethod":"POST"}}
    at throwErrorIfDeploymentFails (/Users/khadijabenammar/Project/yelloan-load-tests/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:74:11)
    at provider.request.then (/Users/khadijabenammar/Project/yelloan-load-tests/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:43:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) 
```

When I checked `serverless-google-cloudfunctions/package/lib/compileFunctions.js`, it does exist  runtime in proprities with `nodejs8`value.

Does someone know what's wrong as it indicates an `invalid runtime`?

Thanks.

**Comment by JannikZed** [comment]
same here. 
```
{"ResourceType":"cloudfunctions.v1beta2.function","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"The request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"runtime","description":"Invalid runtime."}]}],"statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1beta2/projects/brandmeter/locations/europe-west1/functions","httpMethod":"POST"}}
```

**Comment by cocoa-maemae** [comment]
I got the same error if the below configuration.
```
provider:
  name: google
  runtime: nodejs
```
After fixed like the below, the error did not occur.
```
provider:
  name: google
  runtime: nodejs8
```

How about this?

**Comment by gianpaj** [comment]
You can see the runtimes supported here:
https://cloud.google.com/functions/docs/concepts/exec#runtimes

for example `nodejs14` will deploy `Node.js 14 (Beta)`

<img width="1061" alt="Screenshot 2020-12-16 at 00 35 15" src="https://user-images.githubusercontent.com/899175/102285609-8c4f8800-3f2e-11eb-9114-0c28574b436c.png">
