### ISSUE TITLE
Deployment fails with "Not Found" error

### ISSUE THREAD

**Issue by fivepointseven** [serverless/serverless-google-cloudfunctions#82]
When trying to deploy I get this:

```
Error --------------------------------------------------

  Error: Not Found

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Error: Not Found
    at filArgs.reduce (node_modules/serverless-google-cloudfunctions/provider/googleProvider.js:67:33)
    at JWT.OAuth2Client._postRequest (/node_modules/google-auth-library/lib/auth/oauth2client.js:402:3)
    at postRequestCb (node_modules/google-auth-library/lib/auth/oauth2client.js:362:12)
    at Request._callback (node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
From previous event:
    at PluginManager.invoke (.nvm/versions/node/v7.7.2/lib/node_modules/serverless/lib/classes/PluginManager.js:242:22)
    at PluginManager.run (.nvm/versions/node/v7.7.2/lib/node_modules/serverless/lib/classes/PluginManager.js:261:17)
    at variables.populateService.then (.nvm/versions/node/v7.7.2/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Serverless.run (.nvm/versions/node/v7.7.2/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (.nvm/versions/node/v7.7.2/lib/node_modules/serverless/bin/serverless:39:50)
```

**Comment by pmuens** [comment]
Thanks for opening @fivepointseven 👍

🤔 it looks like this is related to the APIs the Google plugin talks to (see [here](https://github.com/serverless/serverless-google-cloudfunctions/blob/09f5e36c3cd46f3f65574fdc214743028b13a29f/provider/googleProvider.js#L67)).

Have you followed the setup process [here](https://serverless.com/framework/docs/providers/google/guide/credentials/) and enabled all the necessary APIs?

**Comment by fivepointseven** [comment]
@pmuens yes, I did. In fact this was a second deployment.
Also, when I rename `service` in serverless.yml to something different, it works

**Comment by pmuens** [comment]
Thanks for getting back @fivepointseven 👍

That sounds like there's a problem in Googles end. Google Cloud Functions is still `beta` and I personally had some related experiences when working on this plugin...

Glad to hear that this doesn't prevent you from deploying altogether.

**Comment by fivepointseven** [comment]
The weird thing is, when I change the `service` to the one that doesn't deploy, I can still deploy fine using `gcloud`.
I'll poke around on weekend and see if I can find the root of the problem

**Comment by pmuens** [comment]
> The weird thing is, when I change the service to the one that doesn't deploy, I can still deploy fine using gcloud.

Hmm. Interesting!

> I'll poke around on weekend and see if I can find the root of the problem

That would be super helpful 💪!

Feel free to ping here if you need any help with that or have smth. to share 👍

**Comment by fivepointseven** [comment]
@pmuens I figured it out. The problem was indeed on Google's side.
I went to **Cloud Console > Deployment Manager**, deleted all deployments created by Serverless and deleted respective storage buckets and deployment with previously failing service name ran successfully.

**Comment by pmuens** [comment]
Great! Thanks for the response @fivepointseven 👍

Glad to hear that you were able to resolve the issue!

**Comment by bryan-dickson** [comment]
not working.  When I curl it, I get the error: 

Deployment failure:
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: ReferenceError: serverless is not defined
    at Object.<anonymous> (/user_code/index.js:5:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getUserFunction (/var/tmp/worker/worker.js:378:24)
    at loadUserCode (/var/tmp/worker/worker.js:434:18)

**Comment by fgilio** [comment]
Thanks @rdev!!!! I was going crazy :P

**Comment by Nesters** [comment]
Is this still an issue on Google's end? Are you sure? I thought Cloud Functions are out of Beta now.

I get it pretty much on every single re-deployment of the existing functions.

**Comment by joshuaquek** [comment]
Thanks @rdev !! Found out that it was a GCP Deployment Manager issue indeed!

**Comment by mabuaisha** [comment]
@rdev That solved my issue, Thanks :)
