### ISSUE TITLE
Error setting up the execution environment for your function. Please try again after a few minutes.

### ISSUE THREAD

**Issue by maciejtreder** [serverless/serverless-google-cloudfunctions#96]
Trying to deploy `google-nodejs` template leads me to 500 error:

```
serverless create --template google-nodejs --path my-service
# setup credentials etc
serverless deploy

Serverless: Checking deployment update progress...
.................................... 
  Error --------------------------------------------------
 
  Deployment failed: RESOURCE_ERROR

     {"ResourceType":"cloudfunctions.v1beta2.function","ResourceErrorCode":"500","ResourceErrorMessage":"Error setting up the execution environment for your function. Please try again after a few minutes."}
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: Deployment failed: RESOURCE_ERROR

     {"ResourceType":"cloudfunctions.v1beta2.function","ResourceErrorCode":"500","ResourceErrorMessage":"Error setting up the execution environment for your function. Please try again after a few minutes."}
    at provider.request.then.catch (/Users/mtreder/Documents/private/work/my-service/node_modules/serverless-google-cloudfunctions/shared/monitorDeployment.js:51:24)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:372:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:403:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:102:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:89:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:42:50)
    at <anonymous>
```

Someone had a chance to successfully deploy this template?

**Comment by MrToph** [comment]
Running into the same issue when using `express` setup for gcp

**Comment by cmbirk** [comment]
Was there any resolution here?

**Comment by ayy-em** [comment]
Is there any solution to this yet?
