### ISSUE TITLE
Credentials path fails to expand tilde to home directory on Windows.

### ISSUE THREAD

**Issue by JadenH** [serverless/serverless-google-cloudfunctions#99]
References: https://github.com/nodejs/node/issues/684
Node Version: 9.5.0

googleProvider.js
```js
let credentials = this.serverless.service.provider.credentials;
const credParts = credentials.split(path.sep);

if (credParts[0] === '~') {
  credParts[0] = os.homedir();
  credentials = credParts.reduce((memo, part) => path.join(memo, part), '');
}

const keyFileContent = fs.readFileSync(credentials).toString();
const key = JSON.parse(keyFileContent);
```

`credentials.split(path.sep)` does not appear to be splitting the path as expected. 
```sh
C:\> node --version
v9.5.0
C:\> node
> let credentials = "~/.gcloud/keyfile.json"
undefined
> const credParts = credentials.split(path.sep);
undefined
> credParts
[ '~/.gcloud/keyfile.json' ]
> credParts[0]
'~/.gcloud/keyfile.json'
> const keyFileContent = fs.readFileSync(credentials).toString();
Error: ENOENT: no such file or directory, open 'C:\~\.gcloud\keyfile.json'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
```

**Comment by aaronkchsu** [comment]
YA this would be super nice to look into.. because it is causing me a lot of problems!

**Comment by dobromyslov** [comment]
This occurs because `path.sep` is `\` when Node.js is running on Windows.
You have to change path separator in your credentials `"~/.gcloud/keyfile.json"` from `/` to windows-style `\` like below.

**serverless.yml:**
```
provider:
  name: google
  ...
  #credentials: ~/.gcloud/keyfile.json # Unix-style path
  credentials: ~\.gcloud\keyfile.json
```
